name: Fetch Notion Content and Commit

on:
  # schedule:
    # - cron: '0 13 * * *'  # 매일 밤 10시 (KST)
  workflow_dispatch:  # 수동 실행 트리거

permissions:
  contents: write  # GITHUB_TOKEN에 write 권한 추가

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # GitHub 토큰을 사용할 수 있도록 활성화

      - name: 최신 LTS Node.js 설정 (Node 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 의존성 설치
        run: npm install

      - name: Notion 글 가져오기 및 MDX 파일 생성
        run: node src/scripts/notion_to_mdx.js
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add .

          # 변경 사항이 있는 경우에만 커밋
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # 한국 표준시(KST)로 현재 날짜 및 시간 설정
          export TZ='Asia/Seoul'
          current_date=$(date +"%Y-%m-%d %H:%M:%S %Z")
          git commit -m "Add new blog post from Notion at ${current_date}"

          # GITHUB_TOKEN을 사용하여 push
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
